### PR TITLE
cargo: update to latest env_logger (0.6.0)

### PR DESCRIPTION
**Pull request by lucab**

### CODE REVIEW

**Comment by crawford** [comment]
Tests failed with the following:

> error: open /tmp/build/inputs/dist/openshift-release/Dockerfile.builder: no such file or directory

/cc @steveej

**Comment by steveej** [comment]
The prow failure is currently expected as the prow job depends on files introduced in #11.

I wonder why the app-sre CI isn't triggered for this PR though. @riuvshin any ideas why that is?

**Comment by steveej** [comment]
Thanks @lucab!

/approve

**Comment by steveej** [comment]
The approval also depends on the `OWNERS` file introduced in #34.

**Review by steveej — APPROVED** [review]

**Pull request merged**
