### PR TITLE
[cargo] bump actix to 3.3.2

### PR DESCRIPTION
**Pull request by PratikMahajan**
this commit bumps the actix dependency to version 3.3.2
this bump required bumping the protobuf dependency to v2.20.0

Also, includes minor code change to update depreciated function
from protobuf dependency.
Updates cincinnati/src/plugins/interface.rs with newly autogenerated
code

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Pull request merged**
