### PR TITLE
Cargo.lock: update to new format

### PR DESCRIPTION
**Pull request by steveej**
This is a syntax only update that was accomplished using
`cargo generate-lockfile --offline`.

### CODE REVIEW

**Comment by steveej** [comment]
I think it's easier to hold this back until we fully switch the switch to Rust 1.47.

/hold

**Comment by LalatenduMohanty** [comment]
@steveeJ this is similar to https://github.com/openshift/cincinnati/pull/277/, isn't it?

**Comment by steveej** [comment]
> this is similar to #277, isn't it?

It is indeed. I'm fine closing either or both. WDYT?

**Comment by LalatenduMohanty** [comment]
> It is indeed. I'm fine closing either or both. WDYT?

I am willing to update #277 . Not sure why you suggested to wait till Rust 1.47

**Comment by steveej** [comment]
> Not sure why you suggested to wait till Rust 1.47

When I updated to that version it automatically updated the lockfile to the new format, that's what initiated the PR. I have since pinned Rust to 1.46 in the cincinnati repo locally to workaround that issue. I'm fine closing this and letting you update #277

**Pull request closed without merging**
