### PR TITLE
Clean up approvers list

### PR DESCRIPTION
**Pull request by aditya-konarde**
Moving on to a new role within Red Hat, so I no longer need this access.

A bunch of other people also moved on to new roles, so removing their access too! 
Thank you for all the collaboration so far! :) 🙌

### CODE REVIEW

**Review by jfchevrette — APPROVED** [review]

**Comment by PratikMahajan** [comment]
please remove unnecessary commits, `68a4a1a` and `aa55737`

**Comment by aditya-konarde** [comment]
@PratikMahajan updated.

**Review by PratikMahajan — APPROVED** [review]
/lgtm 
/hold cancel

**Pull request merged**
