### PR TITLE
OTA-134: remove deploymentconfig from cincinnati

### PR DESCRIPTION
**Pull request by PratikMahajan**
deploymentconfig has been deprecated and we no longer use it. use cincinnati-deployment.yaml as a replacement to deploymentconfig

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
LGTM

**Comment by petr-muller** [comment]
Failures look like the known HEAD fails investigated by David, should be safe to override

**Comment by petr-muller** [comment]
/hold

Meh, the retester starts to kick-in when I LGTM, so holding, unhold as you override

**Comment by PratikMahajan** [comment]
/override ci/prow/customrust-cargo-test
/override ci/prow/cargo-test

overriding known test failures

**Pull request merged**
