### PR TITLE
hack,dist: move pr_check.sh and update README.md

### PR DESCRIPTION
**Pull request by steveej**
/cc @shiywang

### CODE REVIEW

**Comment by shiywang** [comment]
@steveeJ @lucab this one looks good to me, dunno why I still cant label it.
also another thing may irrelevant with this pr is I found `./build-n-push.sh test-*` is no longer exist, also app-sre section there's script no longer exist see my pr https://github.com/openshift/cincinnati/pull/120

**Comment by steveej** [comment]
@shiywang 

> this one looks good to me, dunno why I still cant label it.

I have been in discussion with @stevekuznetsov who might know why you still can't use `/lgtm`.

> also another thing may irrelevant with this pr is I found `./build-n-push.sh test-*` is no longer exist,

It's still there. The script is located with the test images:

```console
$ ll graph-builder/tests/images/build-n-push.sh 
-rwxr-xr-x 1 steveej users 325 May 31 21:17 graph-builder/tests/images/build-n-push.sh
```

**Comment by steveej** [comment]
[test]

**Comment by steveej** [comment]
@shiywang 

> It's still there. The script is located with the test images:

I apologize. I thought the file is in the repo until I noticed that it's in a local gitignore file I use to ignore my local scripts. Please see #121.

**Pull request merged**
