### PR TITLE
[release-4.6] catch up with master and add vendored files and security manifest

### PR DESCRIPTION
**Pull request by steveej**
This catches up with the master branch and adds the files generated by the dist/vendor.sh which is ensured by CI once #333 is merged.

Replaces #341.

### CODE REVIEW

**Comment by wking** [comment]
This will make #316 and #317 redundant parts of the 4.6 history, but Git(Hub) doesn't seem bothered by that.

/lgtm
/retest

**Comment by steveej** [comment]
The failing test isn't supposed to run on this branch.

/override ci/prow/build-only

**Pull request merged**
