### PR TITLE
dist/cargo_test: properly propagate test errors; plugins/edge_add_remove: sort edge-indices on removal

### PR DESCRIPTION
**Pull request by steveej**
This fixes various bugs. PTAL at the commit messages.

### CODE REVIEW

**Comment by wking** [comment]
/hold

Need to review after [the push][1].

[1]: https://github.com/openshift/cincinnati/pull/255#event-3150781526

**Comment by wking** [comment]
Ah, just rebasing around #251 and #252

**Comment by steveej** [comment]
> The following test **failed**, say `/retest` to rerun all failed tests:
> Test name 	Commit 	Details 	Rerun command
> ci/prow/cargo-test 	[71a4fe6](https://github.com/openshift/cincinnati/commit/71a4fe664929aec17c343b6485497d92913255e8) 	[link](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cincinnati/255/pull-ci-openshift-cincinnati-master-cargo-test/1090) 	`/test cargo-test`

With the test errors being effective, we're now seeing

```
thread 'slo::zz_check_slo::_cincinnati_gb_graph_upstream_errors_total_0_' panicked at 'PROM_ENDPOINT unset', graph-builder/tests/slo/mod.rs:77:14
```

which will be properly fixed in #249. In the meantime, I've added a feature gate to the SLO tests in 
44d3c4f .

**Comment by steveej** [comment]
> I don't understand this syntax. Is this "don't worry about the SLO tests", somehow?

it prevents the [slo tests](https://github.com/openshift/cincinnati/tree/master/graph-builder/tests/slo) from being built and executed, except when `--feature test-e2e` is passed to cargo. We only pass this in the [e2e test](https://github.com/openshift/cincinnati/blob/44d3c4fbe083f8f49813d0f92dedba090a0d5df5/dist/Dockerfile.e2e/Dockerfile#L7), which is where we want to run the SLO tests.

The upstream documentation on the syntax is [here](https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg-attribute).

**Comment by wking** [comment]
If CI passes, I'm happy:

/lgtm

Although...

> We only pass this in the e2e test...

Isn't e2e a required test for this PR?

Screenshot from 2020-03-20 14-18-02

Or is that a different e2e test from the one that gets `--feature test-e2e`?

**Comment by steveej** [comment]
> Isn't e2e a required test for this PR?

Yes, but that one is overridable. Maybe the other tests are as well, but I'm not comfortable doing that, while I consider the e2e test semi-blocking.

**Comment by wking** [comment]
/overide e2e

Only failure was [SLO][1], discussed above.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cincinnati/255/pull-ci-openshift-cincinnati-master-e2e/411

**Comment by wking** [comment]
/override ci/prow/e2e

Maybe Prow expects the full path.

**Pull request merged**
