### PR TITLE
dist: unify and cleanup Dockerfiles, refactor scripts, enable private-net-tests

### PR DESCRIPTION
**Pull request by steveej**
Testing the outcome of https://github.com/openshift/release/pull/3935.

TODO
- [x] integrate and close #113 
- [x] update README

Closes #113.

### CODE REVIEW

**Comment by shiywang** [comment]
I am not sure for what reason we use `clux/muslrust:1.34.2-stable` previously, but it seems we git rid of it for good, nice clean up !!

since CI pass, I think it looks good to me !! also agree with https://github.com/openshift/cincinnati/pull/113#issuecomment-499428546

**Comment by steveej** [comment]
@shiywang I incorporated #113 and updated the README again. PTAL

**Comment by steveej** [comment]
> @shiywang: changing LGTM is restricted to assignees, and only openshift/cincinnati repo collaborators may be assigned issues.

Oh, so adding you to the OWNERS in this repo wasn't enough. I filed [a PR in openshift/release](https://github.com/openshift/release/pull/3996) so it should work in the future.

**Review by lucab — APPROVED** [review]
/lgtm

**Pull request merged**
