### PR TITLE
Cargo/deps: bump dkregistry

### PR DESCRIPTION
**Pull request by steveej**
Recent changes in dkregistry implement content verification for image
layers.

### CODE REVIEW

**Comment by lucab** [comment]
@steveeJ my bad, I broke the CI when touching the Dockerfile. https://github.com/openshift/cincinnati/pull/91 should fix it (but I'm not sure how https://github.com/openshift/cincinnati/pull/85 and everything after it was green).

**Comment by steveej** [comment]
> my bad, I broke the CI when touching the Dockerfile. #91 should fix it (but I'm not sure how #85 and everything after it was green).

CI uses what's currently in master. It's a trap I would like to avoid but haven't had any conversation about yet. We need someone to force-merge this.

**Comment by steveej** [comment]
> We need someone to force-merge this.

What I meant is that we need someone to force merge the fix in #91 which has happened by now.

**Pull request merged**
