### PR TITLE
OTA-1348: Fix the failing `compare_quay_result_fixture::_20211124_083150_` test

### PR DESCRIPTION
**Pull request by DavidHurta**
**Fix metadata parser test fixture**
The commit [1] has removed conditional edges from normal edges. This was
done using the `io.openshift.upgrades.graph.previous.remove_regex`
metadata key. The `from` regex field of a conditional risk is appended
to the key's value of a respective `to` version. In other words, the
`OpenshiftSecondaryMetadataParser` parser signals using the metadata
key to the `EdgeAddRemove` plugin what edges to remove from the normal
edges thanks to its knowledge of conditional risks.

Unfortunately, a test fixture was not modified to adhere to the new
changes. The `graph-gb-with-quay-metadata.json` file is supposed to
represent graph with the metadata to act as control data.
This PR fixes that.

[1] https://github.com/openshift/cincinnati/commit/72ed35630cfcb0796473deffdc6c6c2c31ed1155

---

**cincinnati/src/lib.rs: Declare openly Graph's == operator limitations**
Even though conditional edges are part of the Graph type and are
equally as important as the graph itself, they are not taken into
account when two Graps are compared using the `==` operator. Declare
this fact more openly.

### CODE REVIEW

**Comment by DavidHurta** [comment]
Let's be cautious. Modifying the control data to pass the test could be bad in the case I have misunderstood Cincinnati :eyes:

**Review by petr-muller — APPROVED** [review]
Looking at https://github.com/openshift/cincinnati/commit/72ed35630cfcb0796473deffdc6c6c2c31ed1155 the proposed fixture change makes sense to me as a right fix but it would probably be best if @PratikMahajan confirmed.

**Review by PratikMahajan — APPROVED** [review]
/lgtm

**Comment by petr-muller** [comment]
/hold cancel
/override ci/prow/cargo-test
/override ci/prow/customrust-cargo-test

Pratik approved this so let's move this forward.

**Pull request merged**
