### PR TITLE
 graph-builder/registry: asynchronously assemble image metadata

### PR DESCRIPTION
**Pull request by steveej**
Working towards having the tag processing being completely asynchronous.

### CODE REVIEW

**Comment by aditya-konarde** [comment]
Is there a way to get ourselves excluded from the reviewers lottery that prow does? :)

**Comment by vrutkovs** [comment]
@aditya-konarde sorry, app-sre have been added in https://github.com/openshift/cincinnati/pull/169 so that you could merge release-critical PRs.

I don't think there is a simple way to have you excluded, I'll see what we can do

**Comment by vrutkovs** [comment]
https://github.com/openshift/cincinnati/pull/207 should fix e2e - nodes would now be sorted by version. @steveeJ could you check if cherrypicking this commit does the trick?

**Comment by steveej** [comment]
> #207 should fix e2e

The e2e test failure looks unrelated to ordering, and I wouldn't expect this PR to change the order. It merely helps to not block the runtime thread this code runs in.

**Comment by vrutkovs** [comment]
/retest

e2e cluster didn't start properly

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
/hold

so that @LalatenduMohanty could have another look

**Pull request merged**
