### PR TITLE
Update release-4.7 branch

### PR DESCRIPTION
**Pull request by DavidHurta**
Update Cincinnati's release-4.7 branch.

Backport fixes from the master branch without the dependabot configuration.

Pull request related to https://issues.redhat.com/browse/OTA-372.

### CODE REVIEW

**Comment by DavidHurta** [comment]
The tests need to be rerun after the https://github.com/openshift/release/pull/19723 is merged.

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Pull request merged**
