### PR TITLE
quay: tweak read credentials logic

### PR DESCRIPTION
**Pull request by lucab**
This updates the logic for reading credentials, getting rid of Option
handling and using generic path references instead.

/cc @steveeJ

### CODE REVIEW

**Comment by lucab** [comment]
This is extracted from https://github.com/openshift/cincinnati/pull/74, in order to make that PR easier to rebase and review.

**Comment by steveej** [comment]
Are the `tests-net-private` featured tests compatible with this?

**Comment by lucab** [comment]
@steveeJ they build without errors.

**Comment by steveej** [comment]
> they build without errors.

Fair enough ;-)

/lgtm

**Pull request merged**
