### PR TITLE
dist/Dockerfile.build/Dockerfile: use Rust 1.40.0

### PR DESCRIPTION
**Pull request by vrutkovs**
Use latest stable Rust.

rustfmt test added in https://github.com/openshift/release/pull/6901

### CODE REVIEW

**Comment by vrutkovs** [comment]
/skip

e2e still not yet fixed

**Review by steveej — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
Needs a bug if we're going to land this in master since openshift/release#6912.  Or, since Cincy is not part of the release image, we need to PR openshift/release to exclude ourselves from that new requirement.  Personally, for rustfmt, I'm fine waiting until 4.4 splits off master in a few weeks.  But I'm also fine if someone wants to work up the release PR.

**Comment by steveej** [comment]
Blocked on https://github.com/openshift/release/pull/6929 or a valid bugzilla ticket.

**Comment by vrutkovs** [comment]
/skip

e2e is not yet fixed

**Pull request merged**
