### PR TITLE
rename file pr_check.sh to cargo_test.sh

### PR DESCRIPTION
**Pull request by shiywang**

### CODE REVIEW

**Comment by shiywang** [comment]
@steveeJ @lucab this is another catch-22 PR, need to force merge I guess : D

**Comment by steveej** [comment]
> @steveeJ @lucab this is another catch-22 PR, need to force merge I guess : D

You could add a symlink `pr_check.sh -> cargo_test.sh`  as an intermediate state so we don't have to force-merge.

**Comment by steveej** [comment]
Merging this should unblock https://github.com/openshift/release/pull/3895. After merging the latter we can remove the symlink again.

**Review by steveej — APPROVED** [review]
I think these commits should be squashed and then it's good to go.

**Comment by shiywang** [comment]
@steveeJ done

**Review by steveej — APPROVED** [review]
/lgtm

**Pull request merged**
