### PR TITLE
Cargo.lock: Bump with 'cargo generate-lockfile'

### PR DESCRIPTION
**Pull request by wking**
As requested by [this failed rehearsal][1].  Not quite sure what version of Rust/Cargo that is.  Will update the build commands to log that too.

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/6935/rehearse-6935-pull-ci-openshift-cincinnati-master-images/4/build-log.txt

### CODE REVIEW

**Comment by wking** [comment]
I updated openshift/release#6935 to show Rust/Cargo versions.  Turns out these bumps are recommended [by Rust/Cargo 1.41.0][1].  I've pushed 8cd7465 -> 901830c to record that in the commit message.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6935/rehearse-6935-pull-ci-openshift-cincinnati-master-images/6#1:build-log.txt%3A24

**Comment by wking** [comment]
I need to rebase around #202...

**Comment by wking** [comment]
Rebased with 901830c -> 2de6503.

**Comment by wking** [comment]
Version bumps via `git show --word-diff | grep -B3 '^version.*-.*[+]'` (since it's hard to see with all of the format churn):

```diff

[[package]]
name = "actix-connect"
version = [-"0.2.3"-]{+"0.2.5"+}
--

[[package]]
name = "actix-http"
version = [-"0.2.9"-]{+"0.2.11"+}
--

[[package]]
name = "actix-rt"
version = [-"0.2.4"-]{+"0.2.6"+}
--

[[package]]
name = "actix-server"
version = [-"0.6.0"-]{+"0.6.1"+}
--

[[package]]
name = "actix-service"
version = [-"0.4.1"-]{+"0.4.2"+}
--

[[package]]
name = "actix-utils"
version = [-"0.4.5"-]{+"0.4.7"+}
--

[[package]]
name = "actix-web"
version = [-"1.0.5"-]{+"1.0.9"+}
--

[[package]]
name = "actix-web-codegen"
version = [-"0.1.2"-]{+"0.1.3"+}
--

[[package]]
name = "adler32"
version = [-"1.0.3"-]{+"1.0.4"+}
--

[[package]]
name = [-"aho-corasick"-]{+"ahash"+}
version = [-"0.7.6"-]{+"0.2.18"+}
--

[[package]]
name = [-"ansi_term"-]{+"aho-corasick"+}
version = [-"0.11.0"-]{+"0.7.7"+}
--

[[package]]
name = [-"approx"-]{+"ansi_term"+}
version = [-"0.1.1"-]{+"0.11.0"+}
--

[[package]]
name = "arc-swap"
version = [-"0.4.2"-]{+"0.4.4"+}
--

[[package]]
name = "arrayref"
version = [-"0.3.5"-]{+"0.3.6"+}
--

[[package]]
name = "arrayvec"
version = [-"0.4.11"-]{+"0.5.1"+}
--

[[package]]
name = "assert-json-diff"
version = [-"1.0.0"-]{+"1.0.1"+}
--

[[package]]
name = "atty"
version = [-"0.2.13"-]{+"0.2.14"+}
--

[[package]]
name = "autocfg"
version = [-"0.1.6"-]{+"0.1.7"+}
--

[[package]]
name = "awc"
version = [-"0.2.4"-]{+"0.2.8"+}
--

[[package]]
name = "backtrace"
version = [-"0.3.35"-]{+"0.3.43"+}
--

[[package]]
name = "backtrace-sys"
version = [-"0.1.31"-]{+"0.1.32"+}
--

[[package]]
name = "bitflags"
version = [-"1.1.0"-]{+"1.2.1"+}
--

[[package]]
name = "blake2b_simd"
version = [-"0.5.8"-]{+"0.5.10"+}
--

[[package]]
name = "block-padding"
version = [-"0.1.4"-]{+"0.1.5"+}
--

[[package]]
name = "c2-chacha"
version = [-"0.2.2"-]{+"0.2.3"+}
--

[[package]]
name = "cc"
version = [-"1.0.45"-]{+"1.0.50"+}
--

[[package]]
name = "chrono"
version = [-"0.4.7"-]{+"0.4.10"+}
--

[[package]]
name = "colored"
version = [-"1.8.0"-]{+"1.9.2"+}
--

[[package]]
name = "constant_time_eq"
version = [-"0.1.4"-]{+"0.1.5"+}
--

[[package]]
name = "crossbeam-deque"
version = [-"0.7.1"-]{+"0.7.2"+}
--

[[package]]
name = "crossbeam-epoch"
version = [-"0.7.2"-]{+"0.8.0"+}
--

[[package]]
name = "dtoa"
version = [-"0.4.4"-]{+"0.4.5"+}
--

[[package]]
name = "encoding_rs"
version = [-"0.8.17"-]{+"0.8.22"+}
--

[[package]]
name = "failure"
version = [-"0.1.5"-]{+"0.1.6"+}
--

[[package]]
name = "failure_derive"
version = [-"0.1.5"-]{+"0.1.6"+}
--

[[package]]
name = "filetime"
version = [-"0.2.7"-]{+"0.2.8"+}
--

[[package]]
name = "flate2"
version = [-"1.0.11"-]{+"1.0.13"+}
--

[[package]]
name = "futures"
version = [-"0.1.28"-]{+"0.1.29"+}
--

[[package]]
name = "getrandom"
version = [-"0.1.12"-]{+"0.1.14"+}
--

[[package]]
name = "git2"
version = [-"0.10.1"-]{+"0.10.2"+}
--

[[package]]
name = "hashbrown"
version = [-"0.5.0"-]{+"0.6.3"+}
--

[[package]]
name = "http"
version = [-"0.1.18"-]{+"0.1.21"+}
--

[[package]]
name = "humantime"
version = [-"1.2.0"-]{+"1.3.0"+}
--

[[package]]
name = "hyper"
version = [-"0.12.33"-]{+"0.12.35"+}
--

[[package]]
name = "indexmap"
version = [-"1.1.0"-]{+"1.3.1"+}
--

[[package]]
name = "iovec"
version = [-"0.1.2"-]{+"0.1.4"+}
--

[[package]]
name = "itoa"
version = [-"0.4.4"-]{+"0.4.5"+}
--

[[package]]
name = "jobserver"
version = [-"0.1.17"-]{+"0.1.21"+}
--

[[package]]
name = "libc"
version = [-"0.2.62"-]{+"0.2.66"+}
--

[[package]]
name = "libgit2-sys"
version = [-"0.9.1"-]{+"0.9.2"+}
--

[[package]]
name = "lock_api"
version = [-"0.3.1"-]{+"0.3.3"+}
--

[[package]]
name = "memchr"
version = [-"2.2.1"-]{+"2.3.0"+}
--

[[package]]
name = "memoffset"
version = [-"0.5.1"-]{+"0.5.3"+}
--

[[package]]
name = "mime"
version = [-"0.3.13"-]{+"0.3.16"+}
--

[[package]]
name = "miniz_oxide"
version = [-"0.3.2"-]{+"0.3.5"+}
--

[[package]]
name = "mio"
version = [-"0.6.19"-]{+"0.6.21"+}
--

[[package]]
name = "num-traits"
version = [-"0.2.8"-]{+"0.2.11"+}
--

[[package]]
name = "num_cpus"
version = [-"1.10.1"-]{+"1.12.0"+}
--

[[package]]
name = "openssl"
version = [-"0.10.24"-]{+"0.10.27"+}
--

[[package]]
name = "pkg-config"
version = [-"0.3.15"-]{+"0.3.17"+}
--

[[package]]
name = "ppv-lite86"
version = [-"0.2.5"-]{+"0.2.6"+}
--

[[package]]
name = "proc-macro2"
version = [-"1.0.1"-]{+"1.0.8"+}
--

[[package]]
name = "protobuf"
version = [-"2.8.0"-]{+"2.10.1"+}
--

[[package]]
name = "protobuf-codegen"
version = [-"2.8.0"-]{+"2.10.1"+}
--

[[package]]
name = "protoc"
version = [-"2.8.0"-]{+"2.10.1"+}
--

[[package]]
name = "protoc-rust"
version = [-"2.8.0"-]{+"2.10.1"+}
--

[[package]]
name = "publicsuffix"
version = [-"1.5.2"-]{+"1.5.4"+}
--

[[package]]
name = "quick-error"
version = [-"1.2.2"-]{+"1.2.3"+}
--

[[package]]
name = "rand"
version = [-"0.7.0"-]{+"0.7.3"+}
--

[[package]]
name = "rand_core"
version = [-"0.5.0"-]{+"0.5.1"+}
--

[[package]]
name = "redox_users"
version = [-"0.3.1"-]{+"0.3.4"+}
--

[[package]]
name = "regex"
version = [-"1.2.1"-]{+"1.3.4"+}
--

[[package]]
name = "regex-syntax"
version = [-"0.6.11"-]{+"0.6.14"+}
--

[[package]]
name = "reqwest"
version = [-"0.9.20"-]{+"0.9.24"+}
--

[[package]]
name = "rust-argon2"
version = [-"0.5.1"-]{+"0.7.0"+}
--

[[package]]
name = "ryu"
version = [-"1.0.0"-]{+"1.0.2"+}
--

[[package]]
name = "schannel"
version = [-"0.1.15"-]{+"0.1.16"+}
--

[[package]]
name = "security-framework"
version = [-"0.3.1"-]{+"0.3.4"+}
--

[[package]]
name = "security-framework-sys"
version = [-"0.3.1"-]{+"0.3.3"+}
--

[[package]]
name = "serde"
version = [-"1.0.99"-]{+"1.0.104"+}
--

[[package]]
name = "serde_derive"
version = [-"1.0.99"-]{+"1.0.104"+}
--

[[package]]
name = "serde_json"
version = [-"1.0.40"-]{+"1.0.45"+}
--

[[package]]
name = "serde_yaml"
version = [-"0.8.9"-]{+"0.8.11"+}
--

[[package]]
name = "sha2"
version = [-"0.8.0"-]{+"0.8.1"+}
--

[[package]]
name = "signal-hook"
version = [-"0.1.10"-]{+"0.1.13"+}
--

[[package]]
name = "signal-hook-registry"
version = [-"1.1.1"-]{+"1.2.0"+}
--

[[package]]
name = "smallvec"
version = [-"0.6.10"-]{+"0.6.13"+}
--

[[package]]
name = "syn"
version = [-"1.0.5"-]{+"1.0.14"+}
--

[[package]]
name = "thread_local"
version = [-"0.3.6"-]{+"1.0.1"+}
--

[[package]]
name = "tokio-executor"
version = [-"0.1.8"-]{+"0.1.9"+}
--

[[package]]
name = "tokio-reactor"
version = [-"0.1.9"-]{+"0.1.11"+}
--

[[package]]
name = "tokio-sync"
version = [-"0.1.6"-]{+"0.1.7"+}
--

[[package]]
name = "tokio-threadpool"
version = [-"0.1.15"-]{+"0.1.17"+}
--

[[package]]
name = "tokio-timer"
version = [-"0.2.11"-]{+"0.2.12"+}
--

[[package]]
name = "tokio-udp"
version = [-"0.1.3"-]{+"0.1.5"+}
--

[[package]]
name = "toml"
version = [-"0.5.3"-]{+"0.5.6"+}
--

[[package]]
name = "twoway"
version = [-"0.2.0"-]{+"0.2.1"+}
--

[[package]]
name = "unicase"
version = [-"2.4.0"-]{+"2.6.0"+}
--

[[package]]
name = "unicode-normalization"
version = [-"0.1.8"-]{+"0.1.12"+}
--

[[package]]
name = "unicode-segmentation"
version = [-"1.3.0"-]{+"1.6.0"+}
--

[[package]]
name = "unicode-width"
version = [-"0.1.6"-]{+"0.1.7"+}
--

[[package]]
name = "url"
version = [-"2.1.0"-]{+"2.1.1"+}
--

[[package]]
name = "vcpkg"
version = [-"0.2.7"-]{+"0.2.8"+}
--

[[package]]
name = "wasi"
version = [-"0.7.0"-]{+"0.9.0+wasi-snapshot-preview1"+}
--

[[package]]
name = "winapi"
version = [-"0.3.7"-]{+"0.3.8"+}
--

[[package]]
name = "winapi-util"
version = [-"0.1.2"-]{+"0.1.3"+}
```

**Comment by vrutkovs** [comment]
```
 error[E0425]: cannot find value `VERSION_2_8_0` in crate `protobuf`
  --> cincinnati/src/plugins/interface.rs:27:49
   |
27 | const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_0;
   |                                                 ^^^^^^^^^^^^^ help: a constant with a similar name exists: `VERSION_2_10_1`
```

**Comment by wking** [comment]
I've pushed 2de6503 -> da091df, adding `test-case` from #202 based on [rehearsal 7][1].  Still waiting on [rehearsal 8][2] to come back and tell me how to update `cincinnati/src/plugins/interface.rs`.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6935/rehearse-6935-pull-ci-openshift-cincinnati-master-images/7#1:build-log.txt%3A27
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6935/rehearse-6935-pull-ci-openshift-cincinnati-master-images/8

**Pull request closed without merging**
