### PR TITLE
remove the usage of dockerfile.build

### PR DESCRIPTION
**Pull request by PratikMahajan**
removing dockerfile.build as we are no longer using it
for our CI or for any build process.

This PR should merge after 
1. release/[[cincinnati] remove the use of dockerfile.build](https://github.com/openshift/release/pull/18351)
2. cincinnati/[Remove dependency on dockerfile.build](https://github.com/openshift/cincinnati/pull/416)

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
/hold

needs python39 fix

**Comment by PratikMahajan** [comment]
/hold cancel 
python39 fixed

**Pull request merged**
