### PR TITLE
OTA-1338: hack/e2e.sh: Remove the Prometheus token from logs

### PR DESCRIPTION
**Pull request by DavidHurta**
When sensitive data is outputted in logs, such as tokens, the whole log is removed from a CI run's artifacts so as not to disclose potentially sensitive data to the public.

This pull request references https://issues.redhat.com//browse/OTA-1338

### CODE REVIEW

**Comment by DavidHurta** [comment]
The artifacts from the `e2e` CI runs now contain logs from the test script :tada: 

See https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cincinnati/938/pull-ci-openshift-cincinnati-master-e2e/1838253315545108480/artifacts/e2e/openshift-e2e-test/build-log.txt or https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cincinnati/938/pull-ci-openshift-cincinnati-master-customrust-e2e/1838253301288669184/artifacts/e2e/openshift-e2e-test/build-log.txt

**Comment by DavidHurta** [comment]
Originally, the log file would only contain one sentence:
```
This file contained potentially sensitive information and has been removed.
```

See https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cincinnati/938/pull-ci-openshift-cincinnati-master-e2e/1838199581007941632/artifacts/e2e/openshift-e2e-test/build-log.txt

**Review by petr-muller — APPROVED** [review]
LOL good find 

/lgtm
/approve
/meow

**Comment by petr-muller** [comment]
/override ci/prow/cargo-test
/override ci/prow/customrust-cargo-test

our unit tests are busted now

**Pull request merged**
