### PR TITLE
cincinnati/internal/graph_builder: ignore duplicate edges on create_graph

### PR DESCRIPTION
**Pull request by steveej**
This is a quick fix in order to tolerate duplicate edges found in
primary metadata.

---
 
Verified locally that it works with the current public release metadata.

### CODE REVIEW

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
/cc @vrutkovs 

looks fine to me, lets see if unit-tests pass

**Comment by steveej** [comment]
Not sure why the e2e test fail on CI. The e2e suite run from the Justfile works fine locally.

/retest

**Comment by steveej** [comment]
e2e timed out with the initial scrape at:

```
2020-05-14T09:36:30.253183214Z [2020-05-14T09:36:30Z TRACE cincinnati::plugins::internal::graph_builder::release_scrape_dockerv2::registry] [4.3.20-x86_64.bad] Downloading layer sha256:964d57e311cc40e34746a347692678b801ad54144e367eef117e66d43d749c60
```

/retest

@vrutkovs any idea why Quay is so slow?

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Pull request merged**
