### PR TITLE
Bug 1910154: Merge remote-tracking branch 'origin/master' into master-to-release-4.6

### PR DESCRIPTION
**Pull request by wking**
This brings back the `unreadable_file.yaml` fix for rhbz#1910154 and also the `version` parsing for better error messages if the graph-data changes in the future (like we expect it to).  Not sure if this will help with the centos issues #350 is seeing or not.

### CODE REVIEW

**Comment by wking** [comment]
Just bumped to pick up recent master additions.  Diff now is just that master doesn't include vendor code.

```console
$ git diff --stat=300 origin/master..HEAD | grep -v 'vendor/'
 .cargo/config.toml                                                                                                                                                         |     10 +
 rh-manifest.txt                                                                                                                                                            |    367 +
 13657 files changed, 3242103 insertions(+)
```

**Comment by wking** [comment]
* [yaml-lint][1]: `dist/prow_yaml_lint.sh: line 9: type: yamllint: not found`, but these passed in master, so we don't need to block on the 4.6 CI config not using an image with `yamllint`.
* [rustfmt][2]: `dist/prow_rustfmt.sh: line 9: rustup: command not found`, same deal.
* [cargo-test][3]: `dist/cargo_test.sh: No such file or directory`.  I dunno what's up with that; sure looks like the file is there with thi  PR:

    ```console
    $ git ls-tree origin/pr/352 -- dist/cargo_test.sh
    100755 blob 1bd4915a31371a5d47133f3a7bc3a0250735435e    dist/cargo_test.sh
    ```
* [e2e][4]: `failed to initialize the cluster: Cluster operator authentication is still updating`.  That's just a hiccup in OCP coming up; nothing to do with us.

But happily [images passed][5], so we're no longer banging into [`error: failed to select a version for the requirement 'bytes = "=0.5.6"'`][6] and the other stuff we used to be hitting.

/retest

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati/352/pull-ci-openshift-cincinnati-release-4.6-yaml-lint/1352339855870267392
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati/352/pull-ci-openshift-cincinnati-release-4.6-rustfmt-1.46.0/1352339855845101568
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati/352/pull-ci-openshift-cincinnati-release-4.6-cargo-test/1352339855798964224
[4]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati/352/pull-ci-openshift-cincinnati-release-4.6-e2e/1352326702545506304
[5]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati/352/pull-ci-openshift-cincinnati-release-4.6-images/1351971492253929472
[6]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati/352/pull-ci-openshift-cincinnati-release-4.6-images/1351938669774114816#1:build-log.txt%3A65

**Comment by LalatenduMohanty** [comment]
We can close this PR now. @wking WDYT?

**Pull request closed without merging**
