### PR TITLE
Update release-4.8 branch

### PR DESCRIPTION
**Pull request by DavidHurta**
Update Cincinnati's release-4.8 branch.
Backport fixes from the master branch.

Pull request related to https://issues.redhat.com/browse/OTA-372.

### CODE REVIEW

**Comment by vrutkovs** [comment]
I think we want to revert e5eb3c1a935cb4931fd8bc7f6122188e103713f4 in `release-4.x` branches. This would avoid dependabot from sending multiple PRs to these branches. We'll backport dependencies to release-4.x via similar PRs

**Comment by vrutkovs** [comment]
/approve

@LalatenduMohanty any specific concerns about this rebase PR?

**Comment by LalatenduMohanty** [comment]
This is fine. Once it is merged we need to use https://github.com/openshift/cincinnati/tree/master/rh-manifest-generator/src  to commit the vendor files. As OSBS can not solve the vendor dependencies . Here is an example commit from https://github.com/openshift/cincinnati/commit/8c39e8d63a49f5340fcac1db0b93613c8dd1a98a

**Pull request merged**
