### PR TITLE
improve tests around the QuayMetadataFetch plugin

### PR DESCRIPTION
**Pull request by steveej**
This adds missing private-net-tests for the quay metadata fetcher functionality.

For testing I used an API token which I manually created from a dummy organization (https://quay.io/organization/cincinnati-dev).

I'm not happy with the automation level here. After all, the manual image management approach requires to hardcode the remote manifest references in the tests.

---
Ref: https://jira.coreos.com/browse/CIN-4

TODO:
- [x] discuss approach how and if we want to provide secrets for these tests on the CI now

/cc @shiywang

### CODE REVIEW

**Comment by steveeJ** [comment]
flake?

[test]

**Comment by steveej** [comment]
[test]

flake?

**Comment by steveej** [comment]
[test]

more flakes?!

**Comment by steveej** [comment]
In a separate discussion we decided to get the test code merged first and then figure out the infrastructure implications.

**Comment by lucab** [comment]
/hold
/lgtm

@steveeJ holding just in case you changed your mind on how to order this PR and CI changes.

**Comment by steveej** [comment]
> holding just in case you changed your mind on how to order this PR and CI changes.

No change of mind occurred on this :-) Thanks!

/hold cancel

**Pull request merged**
