### PR TITLE
add build-n-push script mentioned in README

### PR DESCRIPTION
**Pull request by steveej**
This script is meant to update the test images on quay.io.

/cc @shiywang

### CODE REVIEW

**Comment by bbguimaraes** [comment]
/lgtm

while we figure out why /cc isn't working for @shiywang.

**Comment by steveej** [comment]
> /lgtm
> 
> while we figure out why /cc isn't working for @shiywang.

Thanks for jumping in @bbguimaraes. The other CI is currently blocked on #119 though, where Shiywang also can't stamp ;-)

**Comment by stevekuznetsov** [comment]
@steveeJ did you contact @openshift/openshift-team-developer-productivity-platform ?

**Comment by steveej** [comment]
@stevekuznetsov 
> did you contact @openshift/openshift-team-developer-productivity-platform ?

@shiywang has done that and has been added to the @openshift/openshift-team-cincinnati team :raised_hands:

**Pull request merged**
